openapi: 3.0.0
info:
  title: API
  version: 1.0.0
servers:
- url: https://example.com
paths:
  /foo:
    get:
      parameters:
      - explode: true
        in: query
        name: order
        required: false
        schema:
          default: ASC
          type: string
        style: form
      responses:
        "200":
          description: OK
components:
  schemas: {}
